tableWithAI =
[
    //[
    //    //helicopter,width,move
    //    //150 350
    //    "HelicopterL", 150, "S",
    //    "HelicopterL", 150, "S",
    //    "HelicopterL", 300, "L",
    //    "HelicopterL", 300, "L",
    //    "HelicopterL", 300, "L",
    //    "ShipL", 175, "S",
    //    "ShipL", 200, "S",
    //    "ShipL", 200, "S",
    //    "ShipL", 240, "S",
    //    "ShipR", 200, "S",
    //    "HelicopterL", 175, "L",
    //    "HelicopterR", 175, "S",
    //    "HelicopterL", 200, "S",
    //    "HelicopterR", 200, "S",
    //    "HelicopterL", 220, "S",
    //    "ShipL", 200, "S",
    //    "ShipL", 240, "S",
    //    "ShipR", 200, "S",
    //    "HelicopterL", 200, "S",
    //    "HelicopterL", 150, "S",
    //    "HelicopterL", 150, "S",
    //    "HelicopterL", 300, "L",
    //    "HelicopterL", 150, "S",
    //    "HelicopterL", 150, "S",
    //    "HelicopterL", 300, "L",
    //    "HelicopterL", 300, "L",
    //    "HelicopterL", 300, "L",
    //    "ShipL", 175, "S",
    //    "ShipL", 200, "S",
    //    "ShipL", 200, "S",
    //    "ShipL", 240, "S",
    //    "ShipR", 200, "S",
    //    "HelicopterL", 175, "L",
    //    "HelicopterR", 175, "S",
    //    "HelicopterL", 200, "S",
    //    "HelicopterR", 200, "S",
    //    "HelicopterL", 220, "S",
    //    "ShipL", 200, "S",
    //    "ShipL", 240, "S",
    //    "ShipR", 200, "S",
    //    "HelicopterL", 200, "S",
    //    "HelicopterL", 150, "S",
    //    "HelicopterL", 150, "S",
    //    "HelicopterL", 300, "L",
    //    "HelicopterL", 300, "L",
    //    "HelicopterL", 300, "L",
    //    "ShipL", 175, "S",
    //    "ShipL", 200, "S",
    //    "ShipL", 200, "S",
    //    "ShipL", 240, "S",
    //    "ShipR", 200, "S",
    //    "HelicopterL", 175, "L",
    //    "HelicopterR", 175, "S",
    //    "HelicopterL", 200, "S",
    //    "HelicopterR", 200, "S",
    //    "HelicopterL", 220, "S",
    //    "ShipL", 200, "S",
    //    "ShipL", 240, "S",
    //    "ShipR", 200, "S",
    //    "HelicopterL", 200, "S",
    //    "HelicopterL", 150, "S",
    //    "HelicopterL", 150, "S",
    //    "HelicopterL", 300, "L",
    //    "HelicopterL", 300, "L",
    //    "HelicopterL", 300, "L",
        
        
    //],
    [
        
        "HelicopterL", 150, "S",
        "HelicopterL", 150, "S",
        "HelicopterL", 300, "L",
        "HelicopterL", 300, "L",
        "HelicopterL", 340, "S",
        "ShipL", 85, "S",
        "ShipL", 350, "S",
        "ShipL", 85, "S",
        "HelicopterL", 340, "S",
        "HelicopterL", 100, "S",
        "HelicopterL", 120, "S",
        "HelicopterR", 100, "S",
        "HelicopterL", 130, "S",
        "HelicopterR", 340, "S",
        "HelicopterL", 350, "S",
        "ShipL", 90, "S",
        "ShipL", 90, "S",
        "ShipR", 330, "S",
        "HelicopterL", 100, "S",
        "HelicopterL", 100, "S",
        "HelicopterL", 350, "S",
        "HelicopterL", 340, "S",
        "HelicopterL", 120, "L",
        "HelicopterL", 150, "L",
        "HelicopterL", 300, "L",
        "HelicopterL", 300, "L",
        "HelicopterL", 300, "L",
        "ShipL", 175, "S",
        "ShipL", 200, "S",
        "ShipL", 200, "S",
        "ShipL", 240, "S",
        "ShipR", 200, "S",
        "HelicopterL", 175, "L",
        "HelicopterR", 175, "S",
        "HelicopterL", 200, "S",
        "HelicopterR", 200, "S",
        "HelicopterL", 220, "S",
        "ShipL", 200, "S",
        "ShipL", 240, "S",
        "ShipR", 200, "S",
        "HelicopterL", 200, "S",
        "HelicopterL", 150, "S",
        "HelicopterL", 150, "S",
        "HelicopterL", 300, "L",
        "HelicopterL", 300, "L",
        "HelicopterL", 300, "L",
        "ShipL", 175, "S",
        "ShipL", 200, "S",
        
    ],
    [
        "HelicopterL", 300, "L",
        "ShipL", 175, "S",
        "ShipL", 200, "S",
        "ShipL", 200, "S",
        "ShipL", 240, "S",
        "ShipR", 200, "S",
        "HelicopterL", 175, "L",
        "HelicopterR", 175, "S",
        "HelicopterL", 200, "S",
        "HelicopterR", 200, "S",
        "HelicopterL", 220, "S",
        "ShipL", 200, "S",
        "ShipL", 200, "S",
        "ShipL", 240, "S",
        "ShipR", 200, "S",
        "HelicopterL", 175, "L",
        "HelicopterR", 175, "S",
        "HelicopterL", 200, "S"

    ],
    [
        "HelicopterL", 300, "L",
        "ShipL", 175, "S",
        "ShipL", 200, "S",
        "ShipL", 200, "S",
        "ShipL", 240, "S",
        "ShipR", 200, "S",
        "HelicopterL", 175, "L",
        "HelicopterR", 175, "S",
        "HelicopterL", 200, "S",
        "HelicopterR", 200, "S",
        "HelicopterL", 220, "S",
        "ShipL", 200, "S",
        "ShipL", 200, "S",
        "ShipL", 240, "S",
        "ShipR", 200, "S",
        "HelicopterL", 175, "L",
        "HelicopterR", 175, "S",
        "HelicopterL", 200, "S"

    ]
  
]